In [4]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
GrdSrch_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-C1_PGCI-GrdSrch-[27]-P3O1/raw-data_2023-04-11_Stykke4.csv")
SobSrch_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-C3_PGCI-SobSrch-[27]-P3O1/raw-data_2023-04-11_Stykke4.csv")
RndSrch_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-A2_PGCI-RndSrch-[27]-P3O1/raw-data_2023-03-10_PtA2-PGCI-RndSrch-[27]-P3O1_Stykke-4.csv")

RndSrch_df.rename(columns={"x1": "s1", "x2": "s2", "x3": "b1", "delta_polymer_mass_pct": "DeltaPolymerMass_pct", "polymer_start_mass_g": "StartPolymerMass_g", "polymer_end_mass_pct": "EndPolymerMass_pct"},inplace=True)

BOpt_8SP_1It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-B1_PGCI-BOpt-[8,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]-P3O1/raw-data_2023-03-15_PtB1-PGCI-BOpt-[8,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]-P3O1-Stykke-4.csv")
BOpt_8SP_2It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-B3_PGCI-BOpt-[8,2,2,2,2,2,2,2,2,2,1]-P3O1/raw-data_2023-03-20_PtB3-PGCI-BOpt-[8,2,2,2,2,2,2,2,2,2,1]-P3O1-Stykke-4.csv")
BOpt_8SP_3It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-B5_PGCI-BOpt-[8,3,3,3,3,3,3,1]-P3O1/raw-data_2023-03-20_PtB5-PGCI-BOpt-[8,3,3,3,3,3,3,1]-P3O1-Stykke-4.csv")
BOpt_16SP_1It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-B2_PGCI-BOpt-[16,1,1,1,1,1,1,1,1,1,1,1]-P3O1/raw-data_2023-03-11_PtB2-PGCI-BOpt-[16,1,1,1,1,1,1,1,1,1,1,1]-P3O1-Stykke-4.csv")
BOpt_16SP_2It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-B4_PGCI-BOpt-[16,2,2,2,2,1]-P3O1/raw-data_2023-03-20_PtB4-PGCI-BOpt-[16,2,2,2,2,1]-P3O1-Stykke-4.csv")
BOpt_16SP_3It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-B6_PGCI-BOpt-[16,3,3,3,2]-P3O1/raw-data_2023-03-20_PtB6-PGCI-BOpt-[16,3,3,3,2]-P3O1-Stykke-4.csv")

BOpt_8SP_1It_df.rename(columns={"x1": "s1", "x2": "s2", "x3": "b1", "delta_polymer_mass_pct": "DeltaPolymerMass_pct", "polymer_start_mass_g": "StartPolymerMass_g", "polymer_end_mass_pct": "EndPolymerMass_pct"},inplace=True)
BOpt_8SP_2It_df.rename(columns={"x1": "s1", "x2": "s2", "x3": "b1", "delta_polymer_mass_pct": "DeltaPolymerMass_pct", "polymer_start_mass_g": "StartPolymerMass_g", "polymer_end_mass_pct": "EndPolymerMass_pct"},inplace=True)
BOpt_8SP_3It_df.rename(columns={"x1": "s1", "x2": "s2", "x3": "b1", "delta_polymer_mass_pct": "DeltaPolymerMass_pct", "polymer_start_mass_g": "StartPolymerMass_g", "polymer_end_mass_pct": "EndPolymerMass_pct"},inplace=True)
BOpt_16SP_1It_df.rename(columns={"x1": "s1", "x2": "s2", "x3": "b1", "delta_polymer_mass_pct": "DeltaPolymerMass_pct", "polymer_start_mass_g": "StartPolymerMass_g", "polymer_end_mass_pct": "EndPolymerMass_pct"},inplace=True)
BOpt_16SP_2It_df.rename(columns={"x1": "s1", "x2": "s2", "x3": "b1", "delta_polymer_mass_pct": "DeltaPolymerMass_pct", "polymer_start_mass_g": "StartPolymerMass_g", "polymer_end_mass_pct": "EndPolymerMass_pct"},inplace=True)
BOpt_16SP_3It_df.rename(columns={"x1": "s1", "x2": "s2", "x3": "b1", "delta_polymer_mass_pct": "DeltaPolymerMass_pct", "polymer_start_mass_g": "StartPolymerMass_g", "polymer_end_mass_pct": "EndPolymerMass_pct"},inplace=True)

ax_BOpt_8SP_1It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-D1_PGCI-BOpt-9,27,1-S2B1O1/raw-data_2023-03-15_Stykke4.csv")
ax_BOpt_8SP_2It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-D2_PGCI-BOpt-9,27,2-S2B1O1/raw-data_2023-03-15_Stykke4.csv")
ax_BOpt_8SP_3It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-D3_PGCI-BOpt-9,27,3-S2B1O1/raw-data_2023-03-15_Stykke4.csv")
ax_BOpt_16SP_1It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-D4_PGCI-BOpt-17,27,1-S2B1O1/raw-data_2023-03-11_Stykke4.csv")
ax_BOpt_16SP_2It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-D5_PGCI-BOpt-17,27,2-S2B1O1/raw-data_2023-03-11_Stykke4.csv")
ax_BOpt_16SP_3It_df = pd.read_csv("/Users/thomasdodd/Library/CloudStorage/OneDrive-MillfieldEnterprisesLimited/Cambridge/PhD/Project-1_BO4BT/ExperimentalSeries-1_PGXOpt/Part-C_HypOptComp_PGCI/Part-D6_PGCI-BOpt-17,27,3-S2B1O1/raw-data_2023-03-11_Stykke4.csv")

In [ ]:
OneShot_Grid_df = GrdSrch_df
OneShot_Quasirandom_df = SobSrch_df
OneShot_Pseudorandom_df = RndSrch_df
Sequential_Bayesian_PI_df = BOpt_8SP_3It_df
Sequential_Bayesian_qLNEI_df = ax_BOpt_8SP_3It_df

In [10]:
Sequential_Bayesian_PI_df["index"] = Sequential_Bayesian_PI_df.index
Sequential_Bayesian_qLNEI_df["index"] = Sequential_Bayesian_qLNEI_df.index

In [16]:
Sequential_Bayesian_PI_df

,mould_position,G_stoichiometry,CA_stoichiometry,IA_stoichiometry,s1,s2,b1,StartPolymerMass_g,EndPolymerMass_pct,DeltaPolymerMass_pct,index
0,A1,1.0,0.989354,0.502368,0.574273,0.838241,0.726713,2.92,86.558126,-13.441874,0
1,A2,1.0,0.138614,1.034845,0.074273,0.338241,0.226713,3.38,85.987091,-14.012909,1
2,A3,1.0,0.470234,0.569463,0.324273,0.088241,0.476713,3.40,86.857362,-13.142638,2
3,A4,1.0,1.695973,0.036986,0.824273,0.588241,0.976713,2.86,88.632357,-11.367643,3
4,A5,1.0,0.676664,0.786529,0.949273,0.213241,0.351713,3.39,87.159687,-12.840313,4
5,A6,1.0,0.999834,0.254052,0.449273,0.713241,0.851713,3.19,86.923355,-13.076645,5
6,B1,1.0,0.081259,1.763554,0.199273,0.963241,0.101713,3.19,89.091765,-10.908235,6
7,B2,1.0,0.931999,0.582790,0.699273,0.463241,0.601713,3.10,86.234312,-13.765688,7
8,B3,1.0,0.091500,1.218500,0.080100,0.429500,0.147600,3.53,89.278178,-10.721822,8
9,B4,1.0,1.345100,0.012800,0.569800,0.799700,0.992900,3.03,91.622741,-8.377259,9
10,B5,1.0,1.335700,0.005500,0.560900,0.305400,0.995800,3.09,90.881200,-9.118800,10
11,B6,1.0,0.144200,1.266400,0.079100,0.651300,0.233100,3.36,88.723825,-11.276175,11
12,C1,1.0,0.151100,0.943300,0.095800,0.232600,0.234700,3.37,87.120193,-12.879807,12
13,C2,1.0,0.139500,1.010900,0.071100,0.312800,0.230000,3.36,87.475473,-12.524527,13
14,C3,1.0,0.144400,0.804700,0.111800,0.026700,0.216200,3.58,86.843673,-13.156327,14
15,C4,1.0,0.143800,0.881000,0.116800,0.119300,0.212900,3.41,86.486662,-13.513338,15
16,C5,1.0,0.128700,0.795600,0.056000,0.020400,0.220300,3.51,86.605535,-13.394465,16
17,C6,1.0,0.942900,0.545300,0.679200,0.438100,0.620800,3.21,87.982575,-12.017425,17
18,D1,1.0,0.927500,0.539000,0.646300,0.461500,0.631200,3.22,86.788613,-13.211387,18
19,D2,1.0,0.984800,0.528500,0.688400,0.478700,0.642600,3.11,87.576801,-12.423199,19
20,D3,1.0,0.812100,0.687600,0.626100,0.578200,0.564300,3.24,85.360793,-14.639207,20
21,D4,1.0,0.801900,0.660900,0.637900,0.470000,0.550400,3.14,87.561111,-12.438889,21
22,D5,1.0,0.777300,0.714400,0.624200,0.557200,0.541200,3.13,86.562527,-13.437473,22
23,D6,1.0,0.752800,0.833600,0.532300,0.983900,0.579800,3.18,88.974175,-11.025825,23
24,E1,1.0,0.668700,0.840700,0.441300,0.980500,0.575500,3.21,88.526132,-11.473868,24
25,E2,1.0,0.719800,0.788300,0.492500,0.881900,0.581100,3.16,87.482123,-12.517877,25
26,E3,1.0,0.833300,0.372000,0.382900,0.657900,0.775600,2.80,83.333167,-16.666833,26
27,E4,1.0,0.773000,0.376600,0.334900,0.646000,0.771200,3.25,82.720178,-17.279822,27
28,E5,1.0,0.777400,0.373800,0.337000,0.647600,0.773100,3.48,79.224303,-20.775697,28

In [12]:
fig = px.scatter_3d(Sequential_Bayesian_PI_df, x='s1', y='s2', z='b1', color='index',width=1300, height=600)
fig.show()

In [17]:
Sequential_Bayesian_qLNEI_df

,mould_position,G_stoichiometry,CA_stoichiometry,IA_stoichiometry,s1,s2,b1,StartPolymerMass_g,EndPolymerMass_pct,DeltaPolymerMass_pct,index
0,A1,1.0,0.989354,0.502368,0.574273,0.838241,0.726713,2.92,86.558126,-13.441874,0
1,A2,1.0,0.138614,1.034845,0.074273,0.338241,0.226713,3.38,85.987091,-14.012909,1
2,A3,1.0,0.470234,0.569463,0.324273,0.088241,0.476713,3.40,86.857362,-13.142638,2
3,A4,1.0,1.695973,0.036986,0.824273,0.588241,0.976713,2.86,88.632357,-11.367643,3
4,A5,1.0,0.676664,0.786529,0.949273,0.213241,0.351713,3.39,87.159687,-12.840313,4
5,A6,1.0,0.999834,0.254052,0.449273,0.713241,0.851713,3.19,86.923355,-13.076645,5
6,B1,1.0,0.081259,1.763554,0.199273,0.963241,0.101713,3.19,89.091765,-10.908235,6
7,B2,1.0,0.931999,0.582790,0.699273,0.463241,0.601713,3.10,86.234312,-13.765688,7
8,B3,1.0,0.528275,0.741425,0.367431,0.490512,0.497430,3.29,86.900726,-13.099274,8
9,B4,1.0,0.414070,0.194428,0.000000,0.131310,0.171861,3.12,85.331179,-14.668821,9
10,B5,1.0,0.295617,0.551447,0.000000,0.349052,0.408767,3.48,88.098928,-11.901072,10
11,B6,1.0,0.663207,0.154200,0.180467,0.105572,0.139475,3.11,85.909610,-14.090390,11
12,C1,1.0,0.457158,0.104212,0.000000,0.216229,0.085685,3.49,84.795072,-15.204928,12
13,C2,1.0,0.478044,0.222409,0.076517,0.000000,0.222409,3.17,85.882807,-14.117193,13
14,C3,1.0,0.500000,0.000000,0.000000,0.130815,0.000000,3.13,83.363601,-16.636399,14
15,C4,1.0,0.489801,0.026951,0.000000,0.321289,0.020398,3.53,82.014853,-17.985147,15
16,C5,1.0,0.487343,0.025314,0.000000,0.000000,0.025314,3.44,84.338759,-15.661241,16
17,C6,1.0,0.500000,0.000000,0.000000,0.350934,0.000000,3.46,84.962705,-15.037295,17
18,D1,1.0,0.690667,0.000000,0.127111,0.325983,0.000000,3.70,86.462789,-13.537211,18
19,D2,1.0,0.500000,0.000000,0.000000,0.438756,0.000000,3.47,83.954244,-16.045756,19
20,D3,1.0,1.127054,0.204863,0.611623,0.000000,0.204863,3.13,87.996295,-12.003705,20
21,D4,1.0,0.500000,0.000000,0.000000,0.234873,0.000000,4.24,85.360702,-14.639298,21
22,D5,1.0,0.500000,0.000000,0.000000,0.000000,0.000000,3.33,84.310627,-15.689373,22
23,D6,1.0,2.000000,0.000000,1.000000,1.000000,0.000000,2.98,89.641380,-10.358620,23
24,E1,1.0,0.597570,0.000000,0.065047,0.000000,0.000000,3.31,85.040221,-14.959779,24
25,E2,1.0,1.568392,0.431608,1.000000,1.000000,0.215804,3.02,88.567042,-11.432958,25
26,E3,1.0,0.461904,0.108026,0.000000,0.417798,0.076193,3.30,85.169882,-14.830118,26
27,E4,1.0,0.000000,1.000000,0.226499,0.000000,1.000000,3.33,87.446276,-12.553724,27
28,E5,1.0,0.000000,1.841916,0.024033,0.841916,1.000000,3.24,90.509550,-9.490450,28

In [13]:
fig = px.scatter_3d(Sequential_Bayesian_qLNEI_df, x='s1', y='s2', z='b1', color='index',width=1300, height=600)
fig.show()